[six_music]
    verbose_name = "BBC 6 Music"
    url = "https://www.bbc.co.uk/programmes/articles/5JDPyPdDGs3yCLdtPhGgWM7/bbc-radio-6-music-playlist"
    type = "playlist"
[six_music_albums]
    verbose_name = "BBC 6 Music Albums"
    url = "https://www.bbc.co.uk/programmes/articles/5JDPyPdDGs3yCLdtPhGgWM7/bbc-radio-6-music-playlist"
    type = "album"
[radio1]
    verbose_name = "BBC Radio 1"
    url = "https://www.bbc.co.uk/programmes/articles/3tqPdBWF9yMbTrfjWvfKV8t/radio-1-playlist"
    type = "playlist"
[dance_anthems]
    verbose_name = "BBC Dance Anthems"
    url = "https://www.bbc.co.uk/programmes/m000qj2w"
    type = "show"
[dance_party_2020]
    verbose_name = "BBC Dance Party 2020"
    url = "https://www.bbc.co.uk/programmes/m000cmjr"
    type = "show"
[dance_party_2021]
    verbose_name = "BBC Dance Party 2021"
    url = "https://www.bbc.co.uk/programmes/m000qx9p"
    type = "show"
